[project]
name = "pyacorn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yun Zhe Wong", email = "yunzhe.wong@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "pyserial>=3.5",
    "pytest>=9.1.1",
]

[build-system]
requires = ["uv_build>=0.11.16,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.17.0",
    "ty>=0.0.84",
]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]